name: responsive_framework
description: Easily make Flutter apps responsive. Automatically adapt UI to different screen sizes. Responsiveness made simple.
version: 0.2.0
homepage: https://codelessly.com
repository: https://github.com/Codelessly/ResponsiveFramework
issue_tracker: https://github.com/Codelessly/ResponsiveFramework/issues
documentation: https://github.com/Codelessly/ResponsiveFramework

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0 # Do not force latest version to prevent dependency conflicts.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: